import { useMemo } from 'react';
import { Copy, FileText } from 'lucide-react';
import { SectionHeader, Surface, toast } from '@/components/ds';
import { Button } from '@/components/ui/button';
import { copyToClipboard } from '@/features/tasks/lib/taskKey';
import { parseNotesMarkdown, splitNoteItem } from '../lib/notesMarkdown';

interface ReleaseNotesPanelProps {
  /** Markdown generated by the API. */
  markdown: string;
}

const HEADING_CLASS = {
  1: 'text-lg font-bold text-slate-900',
  2: 'text-base font-semibold text-slate-900',
  3: 'text-sm font-semibold text-slate-900',
} as const;

/**
 * Generated release notes. The Markdown is parsed into headings, lists and paragraphs and rendered as
 * React text (never as HTML), with a button that copies the Markdown source.
 */
const ReleaseNotesPanel = ({ markdown }: ReleaseNotesPanelProps) => {
  const blocks = useMemo(() => parseNotesMarkdown(markdown), [markdown]);

  const copy = async () => {
    if (await copyToClipboard(markdown)) toast.success('Release notes copied');
    else toast.error('Could not copy. Select the notes and copy them manually.');
  };

  return (
    <Surface as="section" aria-labelledby="release-notes-title" padding="none" className="overflow-hidden">
      <div className="border-b border-slate-100 px-4 py-3 sm:px-5">
        <SectionHeader
          title={<span id="release-notes-title">Release notes</span>}
          icon={<FileText className="size-4" />}
          action={(
            <Button
              variant="outline"
              onClick={() => { void copy(); }}
              disabled={!markdown}
              className="h-11 gap-2 rounded-lg border-slate-300 text-sm text-slate-800 shadow-none md:h-8"
            >
              <Copy className="size-4" aria-hidden /> Copy Markdown
            </Button>
          )}
        />
      </div>
      <div className="space-y-3 px-4 py-4 sm:px-5" data-testid="release-notes">
        {blocks.length === 0 && <p className="text-sm text-slate-600">No notes yet.</p>}
        {blocks.map((block, index) => {
          if (block.kind === 'heading') {
            const Heading = `h${block.level + 2}` as 'h3' | 'h4' | 'h5';
            return <Heading key={index} className={HEADING_CLASS[block.level]}>{block.text}</Heading>;
          }
          if (block.kind === 'list') {
            return (
              <ul key={index} className="space-y-1.5 text-sm text-slate-800">
                {block.items.map((item, itemIndex) => {
                  const { key, title } = splitNoteItem(item);
                  return (
                    <li key={itemIndex} className="flex items-baseline gap-2">
                      <span aria-hidden className="size-1.5 shrink-0 translate-y-[-1px] rounded-full bg-slate-400" />
                      <span className="min-w-0 break-words">
                        {key && <span className="mr-2 font-mono text-xs tabular-nums text-slate-500">{key}</span>}
                        {title}
                      </span>
                    </li>
                  );
                })}
              </ul>
            );
          }
          return (
            <p key={index} className={block.muted ? 'text-sm italic text-slate-600' : 'text-sm text-slate-700'}>{block.text}</p>
          );
        })}
      </div>
    </Surface>
  );
};

export default ReleaseNotesPanel;
